# Generated by Django 5.1.4 on 2024-12-25 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_msg_contact_message_rename_name_contact_name1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name1",
            new_name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
