# Generated by Django 5.1.4 on 2024-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="location",
            field=models.CharField(
                choices=[("home", "Home"), ("office", "Office")],
                default="home",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
