# Generated by Django 5.1.4 on 2024-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_contact_location_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="priority",
            field=models.CharField(default="normal", max_length=10),
        ),
    ]
