# Generated by Django 5.1.4 on 2024-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_contact_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="location",
            field=models.CharField(max_length=10),
        ),
    ]
