# Generated by Django 5.1.4 on 2024-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_contact_newsletter_alter_contact_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="newsletter",
            field=models.BooleanField(),
        ),
    ]
